import type { Metadata } from 'next';
import { Root, RootProviders } from '@/src/components/root';
import { PROJECT_NAME } from '@/src/variables';
import './globals.css';

export const metadata: Metadata = {
    title: {
        default: `${PROJECT_NAME} | Home Page`,
        template: `${PROJECT_NAME} | %s`,
    },
    description: 'Generated by Dmytro Rogkov',
};

type Props = {
    children: React.ReactNode;
};

const RootLayout: React.FC<Props> = ({ children }) => {
    return (
        <RootProviders>
            <Root>{children}</Root>
        </RootProviders>
    );
};

export default RootLayout;
